version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: john
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: codesnippet_hub
    ports:
      - "5432:5432"
